# Generated by Django 5.0.3 on 2024-03-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=400)),
                ('subheadline', models.CharField(max_length=400)),
                ('bio', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='slider_images/')),
            ],
        ),
    ]
