# Generated by Django 5.0.3 on 2024-03-20 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_menuitem_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='category',
            new_name='categories',
        ),
    ]
